version: '3'

services:
  db:
    image: postgres
    environment:
     - POSTGRES_DB=db
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=password
    ports:
     - "5432:5432"
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py createsuperuser && python3 manage.py runserver 0.0.0.0:8000"
    environment:
     - DATABASE_URL=psql://postgres:password@db:5432/db
    volumes:
      - ./src:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
